{"uuid": "cedafc8c-01a1-4d21-a26b-cc1f179b1b15", "children": ["52140db6-3036-4b00-a8ed-7674f211e24f"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: chrome=112.0.5615.139)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0122DCE3+50899]\n\t(No symbol) [0x011BE111]\n\t(No symbol) [0x010C5450]\n\t(No symbol) [0x010B879A]\n\t(No symbol) [0x010B7118]\n\t(No symbol) [0x010B7668]\n\t(No symbol) [0x010C6D22]\n\t(No symbol) [0x0111E631]\n\t(No symbol) [0x0110B8FC]\n\t(No symbol) [0x0111E01C]\n\t(No symbol) [0x0110B6F6]\n\t(No symbol) [0x010E7708]\n\t(No symbol) [0x010E886D]\n\tGetHandleVerifier [0x01493EAE+2566302]\n\tGetHandleVerifier [0x014C92B1+2784417]\n\tGetHandleVerifier [0x014C327C+2759788]\n\tGetHandleVerifier [0x012C5740+672048]\n\t(No symbol) [0x011C8872]\n\t(No symbol) [0x011C41C8]\n\t(No symbol) [0x011C42AB]\n\t(No symbol) [0x011B71B7]\n\tBaseThreadInitThunk [0x75178744+36]\n\tRtlGetAppContainerNamedObjectPath [0x775C587D+253]\n\tRtlGetAppContainerNamedObjectPath [0x775C584D+205]\n\n", "trace": "  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Cong cu va Moi truong phat trien phan mem\\TestLabelStudio\\Nhom9_LabelStudio\\label_studio\\test_selenium\\test_signin.py\", line 17, in test_setup\n    driver.get(\"Labelstudio-env.eba-pbtrgnpm.us-east-1.elasticbeanstalk.com\")\n  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dung DeLL 7537\\AppData\\Roaming\\Python\\Python310\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1683268434471, "stop": 1683268437634}], "start": 1683268434470, "stop": 1683268437760}